// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2020 Narvalo.Org. All rights reserved.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool. Changes to this file may cause incorrect
// behavior and will be lost if the code is regenerated.
//
// Runtime Version: 4.0.30319.42000
// Timestamp:       09/26/2022 10:28:56
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Zorglub.Time.Specialized;

using Zorglub.Time.Core.Intervals;
using Zorglub.Time.Core.Schemas;
using Zorglub.Time.Core.Validation;
using Zorglub.Time.Hemerology;
using Zorglub.Time.Hemerology.Scopes;
using Zorglub.Time.Horology;

/// <summary>Represents the Armenian calendar.
/// <para>This class cannot be inherited.</para></summary>
public sealed partial class ArmenianCalendar : SpecialCalendar<ArmenianDate>
{
    /// <inheritdoc />
    [Pure]
    private protected sealed override ArmenianDate GetDate(int daysSinceEpoch) => new(daysSinceEpoch);
}

/// <summary>Provides common adjusters for <see cref="ArmenianDate"/>.
/// <para>This class cannot be inherited.</para></summary>
public sealed class ArmenianAdjuster : SpecialAdjuster<ArmenianDate>
{
    /// <summary>Initializes a new instance of the <see cref="ArmenianAdjuster"/> class.</summary>
    public ArmenianAdjuster() : base(ArmenianDate.Calendar.Scope) { }

    /// <summary>Initializes a new instance of the <see cref="ArmenianAdjuster"/> class.</summary>
    /// <exception cref="ArgumentNullException"><paramref name="scope"/> is null.</exception>
    internal ArmenianAdjuster(MinMaxYearScope scope) : base(scope) { }

    /// <inheritdoc />
    [Pure]
    private protected sealed override ArmenianDate GetDate(int daysSinceEpoch) => new(daysSinceEpoch);
}

/// <summary>Represents a clock for the Armenian calendar.
/// <para>This class cannot be inherited.</para></summary>
public sealed class ArmenianClock
{
    /// <summary>Represents the clock.</summary>
    private readonly IClock _clock;

    /// <summary>Represents the epoch.</summary>
    private readonly DayNumber _epoch;

    /// <summary>Initializes a new instance of the <see cref="ArmenianClock"/> class.</summary>
    /// <exception cref="ArgumentNullException"><paramref name="clock"/> is null.</exception>
    public ArmenianClock(IClock clock) : this(ArmenianDate.Calendar.Epoch, clock) { }

    /// <summary>Initializes a new instance of the <see cref="ArmenianClock"/> class.</summary>
    /// <exception cref="ArgumentNullException"><paramref name="clock"/> is null.</exception>
    private ArmenianClock(DayNumber epoch, IClock clock)
    {
        _clock = clock ?? throw new ArgumentNullException(nameof(clock));
        _epoch = epoch;
    }

    /// <summary>Gets an instance of the <see cref="ArmenianClock"/> class for the system clock
    /// using the current time zone setting on this machine.</summary>
    public static ArmenianClock Local { get; } = new(SystemClocks.Local);

    /// <summary>Gets an instance of the <see cref="ArmenianClock"/> class for the system clock
    /// using the Coordinated Universal Time (UTC).</summary>
    public static ArmenianClock Utc { get; } = new(SystemClocks.Utc);

    /// <summary>Obtains an instance of the <see cref="ArmenianClock"/> class for the specified
    /// clock.</summary>
    /// <exception cref="ArgumentNullException"><paramref name="clock"/> is null.</exception>
    [Pure]
    public static ArmenianClock GetClock(IClock clock) => new(clock);

    /// <summary>Obtains a <see cref="ArmenianDate"/> value representing the current
    /// date.</summary>
    [Pure]
    public ArmenianDate GetCurrentDate() => new(_clock.Today() - _epoch);
}

/// <summary>Represents the Armenian date.
/// <para><see cref="ArmenianDate"/> is an immutable struct.</para></summary>
public partial struct ArmenianDate :
    IDate<ArmenianDate, ArmenianCalendar>,
    IAdjustable<ArmenianDate>
{
    // NB: the order in which the static fields are written is __important__.

    /// <summary>Represents the schema.</summary>
    private static readonly Egyptian12Schema s_Schema = new();

    /// <summary>Represents the calendar.</summary>
    private static readonly ArmenianCalendar s_Calendar = new(s_Schema);

    /// <summary>Represents the scope.</summary>
    private static readonly MinMaxYearScope s_Scope = s_Calendar.Scope;

    /// <summary>Represents the epoch.</summary>
    private static readonly DayNumber s_Epoch = s_Calendar.Epoch;

    /// <summary>Represents the domain, the interval of supported <see cref="DayNumber"/>.</summary>
    private static readonly Range<DayNumber> s_Domain = s_Calendar.Domain;

    /// <summary>Represents the date adjuster.</summary>
    private static readonly ArmenianAdjuster s_Adjuster = new(s_Scope);

    /// <summary>Represents the smallest possible value of a <see cref="ArmenianDate"/>.</summary>
    private static readonly ArmenianDate s_MinValue = new(s_Domain.Min - s_Epoch);

    /// <summary>Represents the largest possible value of a <see cref="ArmenianDate"/>.</summary>
    private static readonly ArmenianDate s_MaxValue = new(s_Domain.Max - s_Epoch);

    /// <summary>Represents the count of days since the Armenian epoch.</summary>
    private readonly int _daysSinceEpoch;

    /// <summary>Initializes a new instance of the <see cref="ArmenianDate"/> struct to the
    /// specified date parts.</summary>
    /// <exception cref="AoorException">The specified components do not form a valid date or
    /// <paramref name="year"/> is outside the range of years supported by
    /// <see cref="ArmenianCalendar"/>.</exception>
    public ArmenianDate(int year, int month, int day)
    {
        s_Scope.ValidateYearMonthDay(year, month, day);

        _daysSinceEpoch = s_Schema.CountDaysSinceEpoch(year, month, day);
    }

    /// <summary>Initializes a new instance of the <see cref="ArmenianDate"/> struct to the
    /// specified ordinal date parts.</summary>
    /// <exception cref="AoorException">The specified components do not form a valid ordinal date or
    /// <paramref name="year"/> is outside the range of years supported by
    /// <see cref="ArmenianCalendar"/>.</exception>
    public ArmenianDate(int year, int dayOfYear)
    {
        s_Scope.ValidateOrdinal(year, dayOfYear);

        _daysSinceEpoch = s_Schema.CountDaysSinceEpoch(year, dayOfYear);
    }

    /// <summary>Initializes a new instance of the <see cref="ArmenianDate"/> struct.</summary>
    /// <exception cref="AoorException"><paramref name="dayNumber"/> is outside the range of
    /// supported values.</exception>
    public ArmenianDate(DayNumber dayNumber)
    {
        s_Domain.Validate(dayNumber);

        _daysSinceEpoch = dayNumber - s_Epoch;
    }

    /// <summary>Initializes a new instance of the <see cref="ArmenianDate"/> struct.
    /// <para>This method does NOT validate its parameter.</para></summary>
    internal ArmenianDate(int daysSinceEpoch)
    {
        _daysSinceEpoch = daysSinceEpoch;
    }

    /// <summary>Gets the smallest possible value of a <see cref="ArmenianDate"/>.
    /// <para>This static property is thread-safe.</para></summary>
    public static ArmenianDate MinValue => s_MinValue;

    /// <summary>Gets the largest possible value of a <see cref="ArmenianDate"/>.
    /// <para>This static property is thread-safe.</para></summary>
    public static ArmenianDate MaxValue => s_MaxValue;

    /// <summary>Gets the date adjuster.
    /// <para>This static property is thread-safe.</para></summary>
    public static ArmenianAdjuster Adjuster => s_Adjuster;

    /// <inheritdoc />
    public static ArmenianCalendar Calendar => s_Calendar;

    /// <inheritdoc />
    public DayNumber DayNumber => s_Epoch + _daysSinceEpoch;

    /// <inheritdoc />
    public int DaysSinceEpoch => _daysSinceEpoch;

    /// <inheritdoc />
    public Ord CenturyOfEra => Ord.FromInt32(Century);

    /// <inheritdoc />
    public int Century => YearNumbering.GetCentury(Year);

    /// <inheritdoc />
    public Ord YearOfEra => Ord.FromInt32(Year);

    /// <inheritdoc />
    public int YearOfCentury => YearNumbering.GetYearOfCentury(Year);

    /// <inheritdoc />
    public int Year => s_Schema.GetYear(_daysSinceEpoch);

    /// <inheritdoc />
    public int Month
    {
        get
        {
            s_Schema.GetDateParts(_daysSinceEpoch, out _, out int m, out _);
            return m;
        }
    }

    /// <inheritdoc />
    public int DayOfYear
    {
        get
        {
            _ = s_Schema.GetYear(_daysSinceEpoch, out int doy);
            return doy;
        }
    }

    /// <inheritdoc />
    public int Day
    {
        get
        {
            s_Schema.GetDateParts(_daysSinceEpoch, out _, out _, out int d);
            return d;
        }
    }

    /// <inheritdoc />
    public DayOfWeek DayOfWeek => DayNumber.DayOfWeek;

    /// <inheritdoc />
    public bool IsIntercalary
    {
        get
        {
            s_Schema.GetDateParts(_daysSinceEpoch, out int y, out int m, out int d);
            return s_Schema.IsIntercalaryDay(y, m, d);
        }
    }

    /// <inheritdoc />
    public bool IsSupplementary
    {
        get
        {
            s_Schema.GetDateParts(_daysSinceEpoch, out int y, out int m, out int d);
            return s_Schema.IsSupplementaryDay(y, m, d);
        }
    }

    /// <summary>Returns a culture-independent string representation of the current instance.
    /// </summary>
    [Pure]
    public override string ToString()
    {
        s_Schema.GetDateParts(_daysSinceEpoch, out int y, out int m, out int d);
        return FormattableString.Invariant($"{d:D2}/{m:D2}/{y:D4} ({s_Calendar})");
    }

    /// <inheritdoc />
    public void Deconstruct(out int year, out int month, out int day) =>
        s_Schema.GetDateParts(_daysSinceEpoch, out year, out month, out day);

    /// <inheritdoc />
    public void Deconstruct(out int year, out int dayOfYear) =>
        year = s_Schema.GetYear(_daysSinceEpoch, out dayOfYear);
}


public partial struct ArmenianDate // Conversions, adjustments...
{
    #region Counting

    /// <inheritdoc />
    [Pure]
    public int CountElapsedDaysInYear() => s_Schema.CountDaysInYearBefore(_daysSinceEpoch);

    /// <inheritdoc />
    [Pure]
    public int CountRemainingDaysInYear() => s_Schema.CountDaysInYearAfter(_daysSinceEpoch);

    /// <inheritdoc />
    [Pure]
    public int CountElapsedDaysInMonth() => s_Schema.CountDaysInMonthBefore(_daysSinceEpoch);

    /// <inheritdoc />
    [Pure]
    public int CountRemainingDaysInMonth() => s_Schema.CountDaysInMonthAfter(_daysSinceEpoch);

    #endregion
    #region Adjustments

    /// <inheritdoc />
    /// <remarks>See also <seealso cref="Adjuster"/>.</remarks>
    [Pure]
    public ArmenianDate Adjust(Func<ArmenianDate, ArmenianDate> adjuster)
    {
        Requires.NotNull(adjuster);

        return adjuster.Invoke(this);
    }

    //
    // Adjust the day of the week
    //

    /// <inheritdoc />
    [Pure]
    public ArmenianDate Previous(DayOfWeek dayOfWeek)
    {
        var dayNumber = DayNumber.Previous(dayOfWeek);
        if (s_Domain.Contains(dayNumber) == false) Throw.DateOverflow();
        return new ArmenianDate(dayNumber - s_Epoch);
    }

    /// <inheritdoc />
    [Pure]
    public ArmenianDate PreviousOrSame(DayOfWeek dayOfWeek)
    {
        var dayNumber = DayNumber.PreviousOrSame(dayOfWeek);
        if (s_Domain.Contains(dayNumber) == false) Throw.DateOverflow();
        return new ArmenianDate(dayNumber - s_Epoch);
    }

    /// <inheritdoc />
    [Pure]
    public ArmenianDate Nearest(DayOfWeek dayOfWeek)
    {
        var dayNumber = DayNumber.Nearest(dayOfWeek);
        if (s_Domain.Contains(dayNumber) == false) Throw.DateOverflow();
        return new ArmenianDate(dayNumber - s_Epoch);
    }

    /// <inheritdoc />
    [Pure]
    public ArmenianDate NextOrSame(DayOfWeek dayOfWeek)
    {
        var dayNumber = DayNumber.NextOrSame(dayOfWeek);
        if (s_Domain.Contains(dayNumber) == false) Throw.DateOverflow();
        return new ArmenianDate(dayNumber - s_Epoch);
    }

    /// <inheritdoc />
    [Pure]
    public ArmenianDate Next(DayOfWeek dayOfWeek)
    {
        var dayNumber = DayNumber.Next(dayOfWeek);
        if (s_Domain.Contains(dayNumber) == false) Throw.DateOverflow();
        return new ArmenianDate(dayNumber - s_Epoch);
    }

    #endregion
}

public partial struct ArmenianDate // IEquatable
{
    /// <summary>Determines whether two specified instances of <see cref="ArmenianDate"/> are equal.
    /// </summary>
    public static bool operator ==(ArmenianDate left, ArmenianDate right) =>
        left._daysSinceEpoch == right._daysSinceEpoch;

    /// <summary>Determines whether two specified instances of <see cref="ArmenianDate"/> are not
    /// equal.</summary>
    public static bool operator !=(ArmenianDate left, ArmenianDate right) =>
        left._daysSinceEpoch != right._daysSinceEpoch;

    /// <inheritdoc />
    [Pure]
    public bool Equals(ArmenianDate other) => _daysSinceEpoch == other._daysSinceEpoch;

    /// <inheritdoc />
    [Pure]
    public override bool Equals([NotNullWhen(true)] object? obj) =>
        obj is ArmenianDate date && Equals(date);

    /// <inheritdoc />
    [Pure]
    public override int GetHashCode() => _daysSinceEpoch;
}

public partial struct ArmenianDate // IComparable
{
    /// <summary>Compares the two specified instances to see if the left one is strictly earlier
    /// than the right one.</summary>
    public static bool operator <(ArmenianDate left, ArmenianDate right) =>
        left._daysSinceEpoch < right._daysSinceEpoch;

    /// <summary>Compares the two specified instances to see if the left one is earlier than or
    /// equal to the right one.</summary>
    public static bool operator <=(ArmenianDate left, ArmenianDate right) =>
        left._daysSinceEpoch <= right._daysSinceEpoch;

    /// <summary>Compares the two specified instances to see if the left one is strictly later than
    /// the right one.</summary>
    public static bool operator >(ArmenianDate left, ArmenianDate right) =>
        left._daysSinceEpoch > right._daysSinceEpoch;

    /// <summary>Compares the two specified instances to see if the left one is later than or equal
    /// to the right one.</summary>
    public static bool operator >=(ArmenianDate left, ArmenianDate right) =>
        left._daysSinceEpoch >= right._daysSinceEpoch;

    /// <summary>Obtains the earlier date of two specified dates.</summary>
    [Pure]
    public static ArmenianDate Min(ArmenianDate x, ArmenianDate y) => x < y ? x : y;

    /// <summary>Obtains the later date of two specified dates.</summary>
    [Pure]
    public static ArmenianDate Max(ArmenianDate x, ArmenianDate y) => x > y ? x : y;

    /// <summary>Indicates whether this instance is earlier, later or the same as the specified one.
    /// </summary>
    [Pure]
    public int CompareTo(ArmenianDate other) => _daysSinceEpoch.CompareTo(other._daysSinceEpoch);

    [Pure]
    int IComparable.CompareTo(object? obj) =>
        obj is null ? 1
        : obj is ArmenianDate date ? CompareTo(date)
        : Throw.NonComparable(typeof(ArmenianDate), obj);
}

public partial struct ArmenianDate // Math ops
{
#pragma warning disable CA2225 // Operator overloads have named alternates (Usage)
    // Friendly alternates do exist but use domain-specific names.

    /// <summary>Subtracts the two specified dates and returns the number of days between them.
    /// </summary>
    public static int operator -(ArmenianDate left, ArmenianDate right) =>
        left.CountDaysSince(right);

    /// <summary>Adds a number of days to the specified date, yielding a new date.</summary>
    /// <exception cref="OverflowException">The operation would overflow either the capacity of
    /// <see cref="Int32"/> or the range of supported dates.</exception>
    public static ArmenianDate operator +(ArmenianDate value, int days) => value.PlusDays(days);

    /// <summary>Subtracts a number of days to the specified date, yielding a new date.</summary>
    /// <exception cref="OverflowException">The operation would overflow either the capacity of
    /// <see cref="Int32"/> or the range of supported dates.</exception>
    public static ArmenianDate operator -(ArmenianDate value, int days) => value.PlusDays(-days);

    /// <summary>Adds one day to the specified date, yielding a new date.</summary>
    /// <exception cref="OverflowException">The operation would overflow the latest supported date.
    /// </exception>
    public static ArmenianDate operator ++(ArmenianDate value) => value.NextDay();

    /// <summary>Subtracts one day to the specified date, yielding a new date.</summary>
    /// <exception cref="OverflowException">The operation would overflow the earliest supported date.
    /// </exception>
    public static ArmenianDate operator --(ArmenianDate value) => value.PreviousDay();

#pragma warning restore CA2225

    /// <inheritdoc />
    [Pure]
    public int CountDaysSince(ArmenianDate other) =>
        // No need to use a checked context here.
        _daysSinceEpoch - other._daysSinceEpoch;

    /// <inheritdoc />
    [Pure]
    public ArmenianDate PlusDays(int days)
    {
        int daysSinceEpoch = checked(_daysSinceEpoch + days);
        s_Scope.DaysValidator.CheckOverflow(daysSinceEpoch);
        return new(daysSinceEpoch);
    }

    /// <inheritdoc />
    [Pure]
    public ArmenianDate NextDay() =>
        this == s_MaxValue ? Throw.DateOverflow<ArmenianDate>() : new ArmenianDate(_daysSinceEpoch + 1);

    /// <inheritdoc />
    [Pure]
    public ArmenianDate PreviousDay() =>
        this == s_MinValue ? Throw.DateOverflow<ArmenianDate>() : new ArmenianDate(_daysSinceEpoch - 1);
}
