// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2020 Narvalo.Org. All rights reserved.

#nullable enable

namespace Zorglub.TextTemplates;

using System;
using System.IO;
using System.Runtime.Remoting.Messaging;

using EnvDTE;

using Microsoft.VisualStudio.TextTemplating;

/// <summary>Provides a base class for generated text transformations hosted inside Visual Studio.
/// </summary>
public abstract class VSTemplate : TextTransformation
{
    private readonly Lazy<DTE> _dte;
    private readonly Lazy<ITextTemplatingEngineHost> _host;

    private string? _name;
    private string? _namespace;

    /// <summary>Initializes a new instance of the <see cref="VSTemplate"/> class.</summary>
    protected VSTemplate()
    {
        _host = new Lazy<ITextTemplatingEngineHost>(() => HostFactory(this));
        _dte = new Lazy<DTE>(DteFactory);
    }

    /// <summary>Initializes a new instance of the <see cref="VSTemplate"/> class.</summary>
    /// <param name="parent">The parent text transformation.</param>
    protected VSTemplate(TextTransformation parent)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));

        _host = new Lazy<ITextTemplatingEngineHost>(() => HostFactory(parent));
        _dte = new Lazy<DTE>(DteFactory);
    }

    /// <summary>Gets the DTE (Development Tools Environment) service.</summary>
    protected DTE Dte => _dte.Value;

    /// <summary>Gets the templating engine host.</summary>
    protected ITextTemplatingEngineHost VSHost => _host.Value;

    /// <summary>Gets or sets the name of the template.
    /// <para>If none was specified, it is inferred from the template filename.</para></summary>
    protected string Name
    {
        get => _name ??= InferName();

        set
        {
            if (String.IsNullOrWhiteSpace(value))
                throw new ArgumentException("The name can not be null or blank.", nameof(value));

            _name = value;
        }
    }

    /// <summary>
    /// Gets or sets the name of the namespace.
    /// <para>If none was specified, it is inferred from the template location.</para></summary>
    /// </summary>
    protected string Namespace
    {
        get => _namespace ??= InferNamespace();

        set
        {
            if (String.IsNullOrWhiteSpace(value))
                throw new ArgumentException("The namespace can not be null or blank.", nameof(value));

            _namespace = value;
        }
    }

    /// <summary>Initializes the templating class then generates the output text of the
    /// transformation.</summary>
    /// <returns>The output text of the transformation.</returns>
    public string Execute()
    {
        Initialize();
        return TransformText();
    }

    public override string TransformText()
    {
        WriteHeader();
        WriteContent();
        return GenerationEnvironment.ToString();
    }

    //
    // Writers
    //

    protected virtual void WriteContent() { }

    /// <summary>Writes the file header directly into the generated output.</summary>
    protected virtual void WriteHeader() =>
        WriteLine(FormattableString.Invariant(
$"""
// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2020 Narvalo.Org. All rights reserved.

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool. Changes to this file may cause incorrect
// behavior and will be lost if the code is regenerated.
//
// Runtime Version: {Environment.Version}
// Microsoft.VisualStudio.TextTemplating: {Dte.Version}
// </auto-generated>
//------------------------------------------------------------------------------
"""
            ));

    /// <summary>Write the T4 compiler attribute into the generated output.</summary>
    protected void WriteCompilerAttribute() =>
        WriteLine($"""[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.TextTemplating", "{Dte.Version}")""");

    /// <summary>Increases the indent by the default indent.</summary>
    protected void PushIndent() => PushIndent("    ");

    /// <summary>Writes a new (empty) line directly into the generated output.</summary>
    protected void WriteLine() => WriteLine(String.Empty);

    //
    // Private Helpers
    //

    private static ITextTemplatingEngineHost HostFactory(TextTransformation transformation)
    {
        var transformationType = transformation.GetType();
        var hostProperty = transformationType.GetProperty("Host");

        if (hostProperty is null)
            throw new NotSupportedException(
                "Unable to access the templating engine host. "
                + "Please make sure your template includes hostspecific=\"true\" "
                + "attribute in the <#@ template #> directive.");

        return (ITextTemplatingEngineHost)hostProperty.GetValue(transformation, null);
    }

    private DTE DteFactory()
    {
        var serviceProvider = (IServiceProvider)VSHost;
        if (serviceProvider is null)
            throw new NotSupportedException("Host property is null.");

        if (serviceProvider.GetService(typeof(DTE)) is not DTE dte)
            throw new NotSupportedException("Unable to retrieve the DTE (Development Tools Environment) service.");

        return dte;
    }

    private static string InferNamespace() => CallContext.LogicalGetData("NamespaceHint").ToString();

    private string InferName() => Path.GetFileNameWithoutExtension(VSHost.TemplateFile);
}
