name: smoke

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '.config/**'
    - 'eng/**'
    - 'CHANGELOG'
    - 'LICENSE'
    - '**.md'
    - '**.ps1'
    - '**.svg'
    - '**.txt'

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    env:
      # Misc ENV variables.
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: 'skip'

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: dotnet test ./test/Zorglub.Tests --filter "ExcludeFrom!=Smoke&Performance!~Slow"
