name: tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: windows-latest

    env:
      # Misc ENV variables.
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: 'skip'

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: dotnet test test\Zorglub.Tests\ --filter "ExcludeFrom!=Smoke&Performance!~Slow"
